#####SAMPLE DATA#####
227231  20170906T115953.849-0500          ERROR  DWAPGDVQKSAPP01                System.Repository.Repository.Synchronization.Logs.LogEntityManagerWorker 109         78225431-0d59-4196-a85c-16aa5ccf5117           Domain\cognosservice   Error when preparing log file 'C:\ProgramData\Qlik\Sense\Log\Proxy\Trace\DWAPGDVQKSAPP01_Audit_Proxy_2017-09-06T16.59.52Z.log' for archiving              The process cannot access the file '\\apgqliksandev\apgqliksandev\QlikShare\Archived Logs\dwapgdvqksapp01.genpt.net\Proxy\Trace\DWAPGDVQKSAPP01_Audit_Proxy_2017-09-06T16.59.52Z.log' because it is being used by another process.          at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)↵↓   at System.IO.File.InternalDelete(String path, Boolean checkHost)↵↓   at Qlik.Sense.IO.FileSystem.FileCopy(String sourceFileName, String destinationFileName, Boolean overwrite)↵↓   at Repository.Synchronization.Logs.LogEntityManagerWorker.CopyLogfileToArchive(String newRolledLogFile, IList`1 newArchivedLogFiles)                   78225431-0d59-4196-a85c-16aa5ccf5117

###### GROK #####
%{NUMBER:sequence}%{SPACE}%{QLIK_DATE:date}%{NOTSPACE}%{SPACE}%{LOGLEVEL:loglevel}%{SPACE}%{WORD:server}%{SPACE}%{JAVACLASS:classname}%{SPACE}%{NUMBER:thread_id}%{SPACE}%{UUID:uuid}%{SPACE}%{QLIK_LOGIN:login}%{SPACE}%{GREEDYDATA:log_error_message}

##### CUSTOM PATTERN #####
QLIK_DATE %{YEAR}%{MONTHNUM}%{MONTHDAY}[T ]%{HOUR}%{MINUTE}%{SECOND}%{ISO8601_TIMEZONE}
QLIK_LOGIN "%{WORD}[\\\\]%{WORD}

##### OUPTUT ######
{
  "date": "20170906T115953.849-050",
  "server": "DWAPGDVQKSAPP01",
  "login": "DOMAIN\\cognosservice",
  "uuid": "78225431-0d59-4196-a85c-16aa5ccf5117",
  "sequence": "227231",
  "thread_id": "109",
  "classname": "System.Repository.Repository.Synchronization.Logs.LogEntityManagerWorker",
  "loglevel": "ERROR",
  "log_error_message": "Error when preparing log file 'C:\\ProgramData\\Qlik\\Sense\\Log\\Proxy\\Trace\\DWAPGDVQKSAPP01_Audit_Proxy_2017-09-06T16.59.52Z.log' for archiving              The process cannot access the file '\\\\apgqliksandev\\apgqliksandev\\QlikShare\\Archived Logs\\dwapgdvqksapp01.genpt.net\\Proxy\\Trace\\DWAPGDVQKSAPP01_Audit_Proxy_2017-09-06T16.59.52Z.log' because it is being used by another process.          at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)↵↓   at System.IO.File.InternalDelete(String path, Boolean checkHost)↵↓   at Qlik.Sense.IO.FileSystem.FileCopy(String sourceFileName, String destinationFileName, Boolean overwrite)↵↓   at Repository.Synchronization.Logs.LogEntityManagerWorker.CopyLogfileToArchive(String newRolledLogFile, IList`1 newArchivedLogFiles)                   78225431-0d59-4196-a85c-16aa5ccf5117"
}
